# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jira < Formula
  desc ""
  homepage "https://github.com/devashishTaneja/jira-cli"
  version "0.0.3"

  on_macos do
    url "https://github.com/devashishTaneja/jira-cli/releases/download/0.0.3/jira-cli_0.0.3_darwin_all.tar.gz"
    sha256 "7d345149a0a9f4185f9679e8b1d2059f9a63c1a18bb5d4a5bbbf9533d20f1fca"

    def install
      bin.install "jira-cli"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devashishTaneja/jira-cli/releases/download/0.0.3/jira-cli_0.0.3_linux_arm64.tar.gz"
      sha256 "48e549765986d34fb0e6cf928d19a92c1b0804ebf02dd8379e9be482f325194d"

      def install
        bin.install "jira"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/devashishTaneja/jira-cli/releases/download/0.0.3/jira-cli_0.0.3_linux_amd64.tar.gz"
      sha256 "74fbb38b38863d0e86704f424194b0db5c0380979adf7cf1eea6cfdf2ba30f65"

      def install
        bin.install "jira"
      end
    end
  end
end
