# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jira < Formula
  desc ""
  homepage "https://github.com/devashishTaneja/jira-cli"
  version "0.0.5"

  on_macos do
    url "https://github.com/devashishTaneja/jira-cli/releases/download/0.0.5/jira-cli_0.0.5_darwin_all.tar.gz"
    sha256 "405194d628b7a424dde874a669d2515aaedada1b789cf1f78e23dde2aef9390e"

    def install
      bin.install "jira-cli"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devashishTaneja/jira-cli/releases/download/0.0.5/jira-cli_0.0.5_linux_arm64.tar.gz"
      sha256 "bf63cb63760e167ab168aef51b058e3ec430b19405ddd810f94712af137fe26a"

      def install
        bin.install "jira"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/devashishTaneja/jira-cli/releases/download/0.0.5/jira-cli_0.0.5_linux_amd64.tar.gz"
      sha256 "f800a9954411e9fb945e1ff810f6736cbff0132d3cfb2d60c3bcbf1822940fa6"

      def install
        bin.install "jira"
      end
    end
  end
end
