# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jira < Formula
  desc ""
  homepage "https://github.com/devashishTaneja/jira-cli"
  version "0.0.4"

  on_macos do
    url "https://github.com/devashishTaneja/jira-cli/releases/download/0.0.4/jira-cli_0.0.4_darwin_all.tar.gz"
    sha256 "e6c003ddd1ad7fe54900ccf0c44ef6582d1dfa91f22fd9bd5be27a18af52878b"

    def install
      bin.install "jira-cli"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devashishTaneja/jira-cli/releases/download/0.0.4/jira-cli_0.0.4_linux_arm64.tar.gz"
      sha256 "c7fe879ecc4cb2c2efb1cfb4e53608a0d5e48008d388e9f8262240ae5f804348"

      def install
        bin.install "jira"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/devashishTaneja/jira-cli/releases/download/0.0.4/jira-cli_0.0.4_linux_amd64.tar.gz"
      sha256 "7627558e3cf98e5d9c2768bb9899143cff904cd61bf79cdd2cab9d7c12634caf"

      def install
        bin.install "jira"
      end
    end
  end
end
